FROM eclipse-temurin:17-jdk-jammy
WORKDIR /app
COPY target/demo-0.0.1-SNAPSHOT.jar /app/
ARG DATABASE_PASSWORD
ARG DATABASE_URL
ARG DATABASE_USERNAME
ENV DATABASE_PASSWORD=$DATABASE_PASSWORD
ENV DATABASE_URL=$DATABASE_URL
ENV DATABASE_USERNAME=$DATABASE_USERNAME
EXPOSE 8080
ARG DA
RUN ls /app
CMD ["java", "-jar", "demo-0.0.1-SNAPSHOT.jar"]
